// components/FunFact.tsx

import { Panel } from "./panels";

const facts = {
  "Japan": "In 1994, Japan revised its tax laws, allowing the establishment of smaller breweries producing as little as 60,000 liters per year, spurring a boom in microbreweries called 'Ji Bīru.'",
  "Ireland": "Guinness, brewed in nearly 50 countries, has fewer calories than most light beers and is an iconic Irish stout.",
  "Thailand": "Thailand's beer market is led by Singha and Chang, with Singha being the oldest, introduced in 1933.",
  "Switzerland": "Switzerland has over 1,000 breweries, making it one of the countries with the highest brewery density per capita.",
  "Marshall Islands": "",
  "Singapore": "Tiger Beer, launched in 1932, is Singapore's first locally brewed beer and internationally recognized.",
  "Slovenia": "Slovenia is famous for its hop production, particularly Styrian Golding hops, used in brewing globally.",
  "Poland": "Poland is among the top beer-consuming nations, with an annual average of 97.7 liters per person.",
  "Cyprus": "KEO beer, introduced in 1951, is one of Cyprus's most popular beers, brewed with locally sourced ingredients.",
  "Ukraine": "Ukraine's Obolon Brewery is one of Eastern Europe's largest beer producers.",
  "Greenland": "Greenland's first brewery, Godthaab Bryghus, was established in 2006, producing locally inspired beer.",
  "India": "India has one of the lowest per capita beer consumption rates globally, at just 1.2 liters annually.",
  "Macedonia": "Skopje Brewery, founded in 1924, is a prominent beer producer in North Macedonia.",
  "Pakistan": "Murree Brewery, established in 1860, operates under strict regulations to produce beer for non-Muslim communities.",
  "Bangladesh": "Alcohol consumption is restricted, but Crown Beverage produces beer for non-Muslim locals and tourists.",
  "Kenya": "Tusker Lager, introduced in 1922, is a Kenyan beer icon and widely consumed in East Africa.",
  "Zimbabwe": "Delta Corporation produces Zambezi Lager, a popular Zimbabwean beer known for its unique taste.",
  "Abkhazia": "",
  "Haiti": "Prestige Beer, Haiti's flagship beer, has won international awards and is a favorite among locals.",
  "Montenegro": "Nikšićko Pivo is Montenegro's most iconic beer, brewed since 1896 by Trebjesa Brewery.",
  "Ivory Coast": "Solibra Brewery produces popular beers like Flag and Bock in the Ivory Coast.",
  "Mongolia": "Chinggis Beer, named after Genghis Khan, is a strong Mongolian beer with a bold flavor.",
  "Syria": "Before the civil war, Al-Shark and Barada were popular Syrian beer brands.",
  "Uzbekistan": "Sarbast beer is a well-known brand in Uzbekistan's growing beer market.",
  "Iraq": "Farida beer is a notable brand in Iraq, produced despite challenging conditions.",
  "Egypt": "Stella Local beer is widely consumed in Egypt and has historical roots in ancient brewing traditions.",
  "Iran": "Alcohol is banned in Iran, but non-alcoholic, fruit-flavored beers are widely popular.",
  "Finland": "Finland is known for sahti, a traditional farmhouse ale made with juniper berries.",
  "Greece": "Mythos beer, introduced in 1997, is one of Greece's most popular and internationally recognized brands.",
  "Israel": "Israel's craft beer scene began in the early 2000s, with Dancing Camel Brewery being a pioneer.",
  "Czech Republic": "The Czech Republic leads the world in beer consumption per capita, averaging 140 liters annually.",
  "Slovak Republic": "Zlatý Bažant (Golden Pheasant) is one of Slovakia's most famous beer brands.",
  "Hong Kong": "Hong Kong's craft beer scene is thriving, with breweries like Young Master leading the industry.",
  "Chile": "Cristal and Escudo are two of Chile's most popular beer brands, dominating the market.",
  "Mozambique": "Mozambique's 2M beer, pronounced 'dosh-em,' is widely consumed and locally brewed.",
  "Cambodia": "Angkor Beer, named after the iconic temples, is Cambodia's national beer.",
  "Afghanistan": "Alcohol is banned, but during the 1970s, beer production briefly flourished in Afghanistan.",
  "Antigua and Barbuda": "Wadadli Beer, named after Antigua's indigenous name, is a popular local lager.",
  "Jordan": "Carakale Brewery, established in 2010, is Jordan's first craft brewery.",
  "Zambia": "Mosi Lager, named after Victoria Falls, is Zambia's most iconic beer.",
  "Azerbaijan": "Xirdalan beer is Azerbaijan's leading brand, known for its light, refreshing taste.",
  "Nigeria": "Star Lager and Guinness Foreign Extra Stout are two of Nigeria's most consumed beers.",
  "Tunisia": "Celtia, brewed since 1951, is Tunisia's most popular beer brand.",
  "Nagorno-Karabakh": "",
  "Jamaica": "Red Stripe, first brewed in 1928, is Jamaica's most iconic beer, recognized worldwide for its stubby bottle.",
  "United States": "The United States has over 8,800 breweries, making it one of the world's largest craft beer producers.",
  "Germany": "Germany is renowned for its Reinheitsgebot (beer purity law) of 1516, allowing beer to be made only with water, barley, hops, and later yeast.",
  "Denmark": "Carlsberg, one of the world's largest breweries, was founded in Denmark in 1847.",
  "Australia": "Australia's Foster's Lager, though popular internationally, is less consumed locally compared to brands like Victoria Bitter.",
  "Netherlands": "Heineken, one of the world's most famous beer brands, was founded in the Netherlands in 1864.",
  "Spain": "Spain is known for its light lagers like Estrella Damm and Mahou, which are widely consumed across the country.",
  "Venezuela": "Polar Pilsen is Venezuela's most iconic beer, known for its light and refreshing taste.",
  "Mexico": "Mexico is famous for its beers like Corona, Modelo, and Pacifico, often enjoyed with a lime wedge.",
  "Moldova": "Moldova's beer industry is growing, with local brands like Chisinau leading the market.",
  "Portugal": "Portugal's Sagres and Super Bock are the country's two most popular beer brands.",
  "Belarus": "Alivaria Brewery, founded in 1864, is one of Belarus's leading beer producers.",
  "Iceland": "Beer was banned in Iceland until 1989, but now local craft beers like Einstök are popular.",
  "China": "Tsingtao, founded in 1903, is China's most internationally recognized beer brand.",
  "Malta": "Cisk Lager is Malta's most famous beer, brewed since 1929.",
  "Saint Helena": "",
  "Albania": "Tirana Beer, established in 1960, is Albania's oldest and most popular beer.",
  "Isle of Man": "Bushy's Brewery is well-known on the Isle of Man, particularly for its Manx Bitter.",
  "Togo": "Pilsner Lager and Eku Bavaria are two of the most widely consumed beers in Togo.",
  "Trinidad and Tobago": "Carib Lager, brewed since 1950, is Trinidad and Tobago's most iconic beer.",
  "Namibia": "Namibia Breweries Limited produces Windhoek Lager, brewed in adherence to the German Reinheitsgebot.",
  "Burundi": "Amstel and Primus are two of the most popular beers in Burundi.",
  "Dem Rep of Congo": "Primus beer is widely consumed and brewed locally in the Democratic Republic of Congo.",
  "Yemen": "Alcohol is banned in Yemen, but limited production of non-alcoholic beer exists.",
  "Morocco": "Special Flag and Casablanca are two of Morocco's most popular beers, despite strict alcohol regulations.",
  "Belize": "Belikin Beer, brewed since 1971, is the most popular beer in Belize.",
  "Vanuatu": "Tusker Lager is a popular beer in Vanuatu, brewed locally.",
  "Armenia": "Kilikia beer, brewed since 1952, is one of Armenia's leading beer brands.",
  "Sweden": "Sweden has a strong beer culture, with Systembolaget regulating the sale of alcohol, including beer.",
  "Belgium": "Belgium is famous for its Trappist beers, with six of the world's twelve Trappist breweries located there.",
  "Austria": "Austria's beer culture is strong, with Stiegl being one of the country's most iconic beer brands.",
  "El Salvador": "Pilsener and Suprema are two of the most popular beers in El Salvador.",
  "Russia": "Baltika is Russia's largest brewery and one of the leading beer brands in the country.",
  "Dominican Republic": "Presidente is the most popular beer in the Dominican Republic, enjoyed by locals and tourists alike.",
  "Algeria": "Algeria's Heineken brewery produces popular beers like Tango and Amstel.",
  "Lithuania": "Lithuania has a unique farmhouse ale tradition known as 'kaimiškas alus.'",
  "Argentina": "Quilmes is Argentina's most famous beer, brewed since 1890.",
  "Bulgaria": "Zagorka and Kamenitza are two of Bulgaria's most iconic beer brands.",
  "South Korea": "Hite and Cass dominate South Korea's beer market, known for their light and crisp lagers.",
  "Guatemala": "Gallo, introduced in 1896, is Guatemala's most iconic beer brand.",
  "Guam": "Beer consumption is high in Guam, with brands like Budweiser and Heineken being popular.",
  "Palestine": "Taybeh Beer, brewed in the West Bank, is considered the first microbrewery in the Arab world.",
  "Virgin Islands (U.S.)": "The Virgin Islands Pale Ale (VIPA) is a popular beer brewed locally.",
  "French Guiana": "Beer is widely consumed in French Guiana, with popular imports from Brazil and Europe.",
  "Saint Lucia": "Piton Beer, named after the island's famous volcanic peaks, is Saint Lucia'",
  "Laos": "Beerlao is the most popular beer in Laos, often regarded as one of the best beers in Southeast Asia.",
  "Bahamas": "Kalik is the national beer of the Bahamas, named after the sound of cowbells used in Junkanoo celebrations.",
  "Micronesia": "",
  "Burkina Faso": "Brakina is the most popular beer in Burkina Faso, brewed locally.",
  "Tajikistan": "",
  "Hawaii": "Kona Brewing Company, based in Hawaii, produces popular craft beers like Big Wave Golden Ale.",
  "Lesotho": "Maluti Lager is Lesotho's most famous beer, brewed locally and widely consumed.",
  "Croatia": "Ožujsko and Karlovačko are two of Croatia's leading beer brands, enjoyed widely by locals.",
  "Romania": "Ursus and Timișoreana are among Romania's oldest and most popular beer brands.",
  "Latvia": "Aldaris is one of Latvia's largest breweries, producing a wide range of traditional beers.",
  "North Korea": "Taedonggang Beer, brewed in Pyongyang, is North Korea's most prominent beer brand.",
  "Turkey": "Efes Pilsen is Turkey's leading beer brand, known for its crisp, light taste.",
  "Colombia": "Águila and Club Colombia are two of the most popular beer brands in Colombia.",
  "South Africa": "Castle Lager, brewed by South African Breweries, is the country's most iconic beer.",
  "Uruguay": "Pilsen and Patricia are two of Uruguay's most popular beer brands.",
  "Malaysia": "Tiger Beer and Carlsberg are widely consumed in Malaysia, despite strict alcohol regulations.",
  "Puerto Rico": "Medalla Light is Puerto Rico's most popular beer, known for its light and refreshing taste.",
  "Montserrat": "",
  "Botswana": "St. Louis Lager is the most popular beer in Botswana, brewed locally since 1989.",
  "Jersey": "Liberation Brewery produces popular craft beers on the island of Jersey.",
  "Tanzania": "Serengeti and Kilimanjaro Lager are Tanzania's leading beer brands.",
  "East Timor": "",
  "Sint Maarten": "Heineken is one of the most widely consumed beers in Sint Maarten due to its popularity in the Caribbean.",
  "Virgin Islands (British)": "Tortola has a small craft beer scene, with Caribbean-style ales being popular.",
  "Falkland Islands": "",
  "Kyrgyzstan": "Arpa is one of Kyrgyzstan's most popular local beer brands.",
  "Tibet": "Lhasa Beer is Tibet's leading beer, brewed with Himalayan spring water.",
  "Barbados": "Banks Beer is the most popular beer in Barbados, brewed locally since 1961.",
  "Canada": "Molson Canadian and Labatt Blue are two of Canada's most iconic beer brands.",
  "New Zealand": "New Zealand has a vibrant craft beer scene, with Speight's and Monteith's being well-known traditional brands.",
  "Serbia": "Jelen and Lav are two of Serbia's most popular beer brands.",
  "Bermuda": "Bermuda's local beer scene includes the Bermuda Brewing Company, known for its Dockyard Brewing Co. beers.",
  "Philippines": "San Miguel Beer, first brewed in 1890, is the most iconic beer brand in the Philippines.",
  "Indonesia": "Bintang Beer is Indonesia's most popular beer, often compared to Heineken.",
  "Sudan": "Non-alcoholic beers are popular in Sudan due to strict alcohol regulations.",
  "Norfolk Island": "",
  "Cuba": "Cristal and Bucanero are Cuba's most popular beer brands.",
  "Saint Vincent and The Grenadines": "Hairoun Beer, named after the indigenous name for the islands, is the most popular beer.",
  "Tuvalu": "",
  "Liechtenstein": "Liechtenstein's only brewery, Liechtensteiner Brauhaus, produces a range of craft beers.",
  "American Samoa": "",
  "United Kingdom": "The United Kingdom is famous for its ales and bitters, with brands like Guinness, which originated in Ireland, also widely consumed.",
  "Hungary": "Dreher and Soproni are two of Hungary's most popular beer brands.",
  "Norway": "Norway has a strong craft beer scene, with Ringnes being one of the largest traditional breweries.",
  "Taiwan": "Taiwan Beer, brewed with local Ponlai rice, is the most iconic beer in the country.",
  "Brazil": "Brahma, Skol, and Antarctica are Brazil's top beer brands, known for their light lagers.",
  "Luxembourg": "Bofferding and Diekirch are two of Luxembourg's most popular beer brands.",
  "Peru": "Cusqueña, brewed near Machu Picchu, is one of Peru's most iconic beers.",
  "Ecuador": "Pilsener is the most consumed beer in Ecuador, known for its light and refreshing taste.",
  "Costa Rica": "Imperial is Costa Rica's national beer, widely consumed by locals and tourists.",
  "Slovakia": "Zlatý Bažant (Golden Pheasant) is Slovakia's most popular beer brand.",
  "Kosovo": "Peja Beer is one of the most popular beer brands in Kosovo.",
  "Oman": "",
  "Paraguay": "Pilsen and Bavaria are two of the most consumed beer brands in Paraguay.",
  "Vietnam": "Bia Saigon and 333 are two of Vietnam's most iconic beer brands.",
  "Honduras": "Salva Vida is one of the most popular beers in Honduras, brewed since 1916.",
  "Uganda": "Nile Special, brewed from local sorghum, is Uganda's most famous beer.",
  "United Arab Emirates": "Alcohol consumption is heavily regulated, but imported beers are available in licensed venues.",
  "San Marino": "",
  "Kazakhstan": "Shymkentskoe and Karagandinskoe are two popular beer brands in Kazakhstan.",
  "Lebanon": "Almaza is Lebanon's leading beer brand, brewed since 1933.",
  "Macau": "Macau Beer is the most iconic local beer, brewed using water from the region.",
  "Italy": "Peroni and Birra Moretti are Italy's most famous beer brands, known internationally.",
  "France": "Kronenbourg 1664 and Fischer are two of France's most well-known beer brands.",
  "Estonia": "Saku and A. Le Coq are Estonia's most popular beer brands.",
  "Faroe Islands": "Føroya Bjór is the Faroe Islands' only brewery, producing a range of traditional beers.",
  "Andorra": "Andorra has a small but growing craft beer scene with locally brewed brands.",
  "Ascension Island": "",
  "Bolivia": "Paceña is Bolivia's most popular beer, brewed in La Paz.",
  "Cayman Islands": "Caybrew is the most popular beer brewed in the Cayman Islands.",
  "Panama": "Panama Lager and Balboa are two of the most consumed beers in the country.",
  "Bosnia and Herzegovina": "Sarajevsko Pivo, brewed since 1864, is Bosnia and Herzegovina's most famous beer.",
  "Saudi Arabia": "Alcohol is banned, but non-alcoholic beers are widely available.",
  "Ghana": "Star Lager and Club Beer are two of Ghana's most popular beer brands.",
  "Mauritius": "Phoenix Beer is the most iconic beer brand in Mauritius.",
  "Nepal": "Gorkha Beer and Everest Beer are two of Nepal's leading beer brands.",
  "Vatican City": "",
  "Papua New Guinea": "SP Lager is the most widely consumed beer in Papua New Guinea.",
  "Monaco": "Monaco Beer is a unique local beer blending light beer with lemonade and grenadine.",
  "Nicaragua": "Toña is the most popular beer in Nicaragua, brewed locally.",
  "Fiji Islands": "Fiji Gold and Fiji Bitter are the most widely consumed beers in the Fiji Islands."
}


interface FunFactProps {
  countryName: string;
  onClose: () => void;
}

const FunFact: React.FC<FunFactProps> = ({ countryName, onClose }) => {
  const fact = facts[countryName];

  if (!fact) {
    return null;
  }

  return (
    <Panel
      title="Did you know?"
      onClose={onClose}
      position="bottom-center"
    >
      <p className="text-gray-300">
        {fact}
      </p>
    </Panel>
  );
};

export default FunFact;